theme: jekyll-theme-minimal
title: jonathan ng
description: designer + developer
logo: logo.png
aboutvideo: about.mp4
linkedin: https://linkedin.com/in/ngkjon
email: mailto:jng.cad@gmail.com
spotify: https://open.spotify.com/user/ddojo?si=kk3RCQvqSyKX2s11DuTS3g